services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9093:9093"
      - "9094:9094"  # For external listener
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE,EXTERNAL
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9093,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_INTERNAL: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_EXTERNAL: EXTERNAL://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_INSIDE: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_EXTERNAL: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_HOSTNAME: kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-network


networks:
  kafka-network:
    driver: bridge
